export const CODES_LIST_REQUEST = "CODES_LIST_REQUEST";
export const CODES_LIST_SUCCESS = "CODES_LIST_SUCCESS";
export const CODES_LIST_FAIL = "CODES_LIST_FAIL";


export const CODES_CREATE_REQUEST = "CODES_CREATE_REQUEST";
export const CODES_CREATE_SUCCESS = "CODES_CREATE_SUCCESS";
export const CODES_CREATE_FAIL = "CODES_CREATE_FAIL";

export const CODE_UPDATE_REQUEST = "CODE_UPDATE_REQUEST";
export const CODE_UPDATE_SUCCESS = "CODE_UPDATE_SUCCESS";
export const CODE_UPDATE_FAIL = "CODE_UPDATE_FAIL";

export const CODE_DELETE_REQUEST = "CODE_DELETE_REQUEST";
export const CODE_DELETE_SUCCESS = "CODE_DELETE_SUCCESS";
export const CODE_DELETE_FAIL = "CODE_DELETE_FAIL";

export const CODES_STATS_REQUEST = "CODES_STATS_REQUEST";
export const CODES_STATS_SUCCESS = "CODES_STATS_SUCCESS";
export const CODES_STATS_FAIL    = "CODES_STATS_FAIL";