export const FOLDERS_LIST_REQUEST = "FOLDERS_LIST_REQUEST";
export const FOLDERS_LIST_SUCCESS = "FOLDERS_LIST_SUCCESS";
export const FOLDERS_LIST_FAIL = "FOLDERS_LIST_FAIL";


export const FOLDER_CREATE_REQUEST = "FOLDER_CREATE_REQUEST";
export const FOLDER_CREATE_SUCCESS = "FOLDER_CREATE_SUCCESS";
export const FOLDER_CREATE_FAIL = "FOLDER_CREATE_FAIL";

export const FOLDER_UPDATE_REQUEST = "FOLDER_UPDATE_REQUEST";
export const FOLDER_UPDATE_SUCCESS = "FOLDER_UPDATE_SUCCESS";
export const FOLDER_UPDATE_FAIL = "FOLDER_UPDATE_FAIL";

export const FOLDER_DELETE_REQUEST = "FOLDER_DELETE_REQUEST";
export const FOLDER_DELETE_SUCCESS = "FOLDER_DELETE_SUCCESS";
export const FOLDER_DELETE_FAIL = "FOLDER_DELETE_FAIL";